### PR TITLE
Added lang-ro.js (Romanian translation)

### PR DESCRIPTION
**Pull request by amacara1**
Added Romanian translation

### CODE REVIEW

**Comment by jmoenig** [comment]
Yay!! It looks like I could just also use this translation for the main Snap trunk?

**Comment by bromagosa** [comment]
Yes! I asked @amacara1 to send you a pull request, but I guess you can just grab the file :)

**Comment by jmoenig** [comment]
Oh, good! @amacara1, if you send a pull-request to the main Snap trunk I'll pull it! Thx

**Comment by amacara1** [comment]
I’ve just requested a pull. 

HTH,
Cristian.

**Pull request closed without merging**
