### PR TITLE
fixed #60 (shadow color for non-flat block labels)

### LINKED ISSUE #60: wrong shadow color in block labels
non-flat blocks use a wrong shadow color in their labels, it's too dark and only uses gray instead of a darker shade of the current block color. I noticed this in some screen shots you've been posting in Twitter earlier today :-)

Luckily this is an easy (not to say trivial) fix, so I'll be issuing a pull-request right away.

BTW, I love your (how do you call it?) "decorator" pattern! It makes it *very* easy for me to find my way around the codebase!

### PR DESCRIPTION
**Pull request by jmoenig**
just a tiny glitch…

### CODE REVIEW

**Comment by jmoenig** [comment]
Okay, turns out this _also_ fixes another glitch: When zooming blocks the labels don't resize inside the zoom-blocks dialog box. I'm not going to open another issue for this, since - as I've just now discovered - this little pull request also fixes this. Haha, talk about efficiency!!

**Comment by bromagosa** [comment]
Thank you, Jens! I'm pulling this today, and will release it this week when I (hopefully) manage to hunt down an annoying bug.

**Comment by jmoenig** [comment]
Thanks, Bernat! What's the annoying bug?

**Comment by bromagosa** [comment]
It's related to the serial port plugin, and I think it's also related to #39 but I'm not sure.

The problem is that communication with the board sometimes just randomly drops, and there is no way to reconnect back unless you save the project, quit Snap4Arduino and start over.

The ideal behavior would be for the software to detect when the connection dropped and try to reconnect automatically, maybe showing a dialog that says something like "hold on, trying to reconnect".

**Comment by jmoenig** [comment]
Ugh... that _is_ nasty, indeed. Could you maybe "ping" the connection every once and so often using the ide's `step` method and the `fps` property to find out whether it's still alive?

**Comment by bromagosa** [comment]
Yeah, something like that could work, I was thinking of using something like [this](http://firmata.org/wiki/Protocol#Query_Firmware_Name_and_Version), because Firmata doesn't implement a ping message.

Wish me luck! ;)

**Comment by jmoenig** [comment]
Ugh, yeah, that really sucks. You could also (maybe?) get a return code for every primitive that's not a function itself, and if you're not getting any that would indicate that the connection dropped... Hmm... or - better yet - fix the real problem :-) <-- sarcasm

**Comment by bromagosa** [comment]
I really don't want to modify Firmata... we're always preaching that Snap4Arduino uses StandardFirmata, which comes bundled with the Arduino IDE.

I guess I'll have to either go the `queryFirmware` way or try fixing the real problem! :p

**Comment by jmoenig** [comment]
good luck!

**Pull request merged**
